# Generated by Django 5.2.6 on 2025-09-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.URLField()),
                ('paths', models.JSONField(default=dict)),
                ('selectors', models.JSONField(default=dict)),
                ('custom_logic', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Web Source',
                'verbose_name_plural': 'Web Sources',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(unique=True)),
                ('raw_content', models.TextField()),
                ('summary_proposal_details', models.TextField(blank=True, null=True)),
                ('summary_status_and_outcome', models.TextField(blank=True, null=True)),
                ('summary_citizen_impact', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.websource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
