# Generated by Django 5.2.6 on 2025-09-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary_citizen_impact',
            new_name='summary_citizen_impact_en',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='summary_proposal_details',
            new_name='summary_citizen_impact_fi',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='summary_status_and_outcome',
            new_name='summary_citizen_impact_sv',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title_fi',
        ),
        migrations.AddField(
            model_name='article',
            name='summary_proposal_details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_proposal_details_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_proposal_details_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_status_and_outcome_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_status_and_outcome_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_status_and_outcome_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
