# Generated by Django 5.2.6 on 2025-09-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_summary_citizen_impact_article_summary_citizen_impact_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subject_fi',
            field=models.CharField(default='x', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='subject_sv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_fi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
