# Generated by Django 5.2.6 on 2025-09-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_subject_en_article_subject_fi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='progress_stages',
            field=models.JSONField(default=list),
        ),
    ]
