# Generated by Django 5.2.6 on 2025-09-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_current_stage_article_progress_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary_status_and_outcome_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_status_and_outcome_fi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_status_and_outcome_sv',
        ),
    ]
