# Generated by Django 5.2.6 on 2025-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_summary_status_and_outcome_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True)),
                ('article_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stage Summary',
                'verbose_name_plural': 'Stage Summaries',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='stage_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='stage_fi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='stage_sv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='state_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='state_fi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='state_sv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
