# Generated by Django 5.2.6 on 2025-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_stagesummary_article_stage_en_article_stage_fi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='votes_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='votes_undecided',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='votes_yes',
            field=models.IntegerField(default=0),
        ),
    ]
