# Generated by Django 5.2.6 on 2025-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_votes_no_article_votes_undecided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pct_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pct_undecided',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pct_yes',
            field=models.IntegerField(default=0),
        ),
    ]
