# Generated by Django 5.2.6 on 2025-12-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_pct_no_article_pct_undecided_article_pct_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_voted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='primary_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
