# Generated by Django 5.2.6 on 2025-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_last_voted_at_article_primary_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='primary_category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
